**# 读写文件**

**1. 加载和保存张量**

* 对于单个张量，可以直接调用load和save函数分别读写它们。 这两个函数都要求我们提供一个名称，save要求将要保存的变量作为输入。

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')

* 可以将存储在文件中的数据读回内存。

In [3]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

* 可以存储一个张量列表，然后把它们读回内存。

In [4]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

* 可以写入或读取从字符串映射到张量的字典。当要读取或写入模型中的所有权重时，会很方便。

In [5]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

**2. 加载和保存模型参数**

* 深度学习框架提供了内置函数来保存和加载整个网络。需要注意的一个重要细节是，这将保存模型的参数而不是保存整个模型。 
* 例如，如果有一个3层多层感知机，需要单独指定架构。因为模型本身可以包含任意代码，所以模型本身难以序列化。因此，为了恢复模型，需要用代码生成架构，然后从磁盘加载参数。

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

* 将模型的参数存储在一个叫做“mlp.params”的文件中。

In [7]:
torch.save(net.state_dict(), 'mlp.params')

* 为了恢复模型，实例化了原始多层感知机模型的一个备份。 这里不需要随机初始化模型参数，而是直接读取文件中存储的参数。

In [8]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

* 由于两个实例具有相同的模型参数，在输入相同的X时， 两个实例的计算结果应该相同。

In [9]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])