**# 数据操作实现**

In [ ]:
# 导入Pytorch
import torch

*  张量表示一个数值组成的数组，这个数组可能有多个维度

In [ ]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

*  可以通过张量的**shape**属性来访问张量的**形状**和张量中**元素的总数**

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x.numel()

12

*  要改变一个张量的形状而不改变其元素的数量和元素值，可以调用**reshape**函数

In [ ]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

* 使用全0、全1、其他常量或从特定分布汇总随机采样的数字

In [ ]:
torch.zeros((2,3,4))    

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones((3,2,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

*  通过提供包含数值的Python列表(或嵌套循环)来为所需要的张量中的每个元素赋予确定值

In [ ]:
a = torch.tensor([1,2,3,4])  # 表示一维度
print(a)
print(a.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [ ]:
b = torch.tensor([[1,2,3,4],[2,3,1,4],[4,3,2,1]]) # 表示二维
print(b) 
print(b.shape)

tensor([[1, 2, 3, 4],
        [2, 3, 1, 4],
        [4, 3, 2, 1]])
torch.Size([3, 4])


In [ ]:
c = torch.tensor([[[1,2,3,4],[2,3,1,4],[4,3,2,1]]]) # 表示三维
print(c)
print(c.shape)

tensor([[[1, 2, 3, 4],
         [2, 3, 1, 4],
         [4, 3, 2, 1]]])
torch.Size([1, 3, 4])


*  常见的标准算术运算符(+,-,*,/,**)都可以被升级为按元素运算

In [ ]:
x = torch.tensor([1.0,2,3,4])   # 存在1.0，就会显示浮点
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, x**y

(tensor([3., 4., 5., 6.]),
 tensor([-1.,  0.,  1.,  2.]),
 tensor([2., 4., 6., 8.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1.,  4.,  9., 16.]))

*  可以将多个张量**连结**在一起

In [ ]:
X = torch.arange(12, dtype = torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0), torch.cat((X,Y),dim=1)   # dim=0 可以视为按行合并， dim=1 可以视为按列合并; 在三维中，dim=2 按照深度以dim

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

* 通过**逻辑元算符**构建二元张量

In [ ]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

* 对张量中的所有元素进行求和会产生一个只有一个元素的张量

In [ ]:
X.sum()

tensor(66.)

*  即使形状不同，仍然可以通过调用**广播机制(broadcasting,mechanism)**来执行按元素操作
*  例如下述的a和b，会自动补充:

```
   a -> tensor([[0, 0]
                [1, 1]
                [2, 2])

   b -> tensor([[0, 1]
                [0, 1]
                [0, 1])
```


In [ ]:
A = torch.arange(3).reshape((3,1))
B = torch.arange(2).reshape((1,2))
print(A)
print(B)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [ ]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

*  可以用**[-1]**选择最后一个元素，可以用**[1:3]**选择第二个和第三个元素

In [ ]:
Z = torch.arange(12, dtype = torch.float32).reshape(3,4)
Z

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
Z[-1]

tensor([ 8.,  9., 10., 11.])

In [ ]:
Z[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

*  除读取外，也可以通过指定索引来将元素写入矩阵

In [ ]:
Z[1,2] = 9  # 原值为6，修改为9
Z

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# 区域赋值
Z[0:2, :] = 12  # 第0行和第一行的所有列
Z 

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

* 运行一些操作可能会导致为新结果分配内存

In [ ]:
before = id(Y)
Y = Y + X
id(Y) ==before

False

In [ ]:
# 执行原地操作
Z = torch.zeros_like(Y)  # 创建一个和Y形状相同的全0矩阵
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))

id(Z): 140073336781040
id(Z): 140073336781040


* 如果在后续计算中没有重复使用X，我们也可以使用 **X[:] = X+Y** 或 **X += Y** 来减少操作的内存开销

In [ ]:
before = id(X)
X += Y
id(X) == before

True

* 转换为Numpy张量

In [ ]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

* 将大小为1的张量转换为Python标量

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)