**# 线性代数实现**

*  **torch中一维张量就是行向量，而列向量实际是矩阵**
*  **但有时，行向量会按照列向量参与数学运算，参考 矩阵-向量 乘法**

* 标量由只有一个元素的张量表示

In [78]:
import torch

x = torch.tensor([3.0]) 
y = torch.tensor([2.0])

x + y, x * y, x /y , x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

* 可以将向量视为标量组成的列表

In [79]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

* 通过张量的索引来访问任一元素

In [80]:
x[3]

tensor(3)

* 访问张量的长度

In [81]:
len(x)

4

*  只有一个轴的张量，形状只有一个元素

In [82]:
x.shape

torch.Size([4])

* 通过指定两个分量m和n来创建一个形状为m x n的矩阵

In [83]:
A = torch.arange(20).reshape(4,5) 
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

* 矩阵的转置

In [84]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

* 对称矩阵 A 等于其转置

In [85]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [86]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

* 就像向量是标量的推广，矩阵是向量的推广一样，可以构建具有更多轴的数据结构

In [87]:
X = torch.arange(24).reshape(2,3,4)  
# 表示2个 3x4 的矩阵， 越往后维度越低
# 例如（2，3，4，5） 表示2个三维张量， 每个三维张量具有3个 4x5 矩阵
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

* 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [88]:
A = torch.arange(20, dtype=torch.float32).reshape(4,5)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B，即修改B的值不会影响A的值
print(A) 
print(A + B)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.],
        [20., 22., 24., 26., 28.],
        [30., 32., 34., 36., 38.]])


* 两个矩阵按元素乘法称为 哈达玛积

In [89]:
A * B # 两个矩阵对应位置元素作运算

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.],
        [225., 256., 289., 324., 361.]])

In [90]:
a = 2  # 标量和每一个元素作运算
print(a + A)
print(a * A)

tensor([[ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16.],
        [17., 18., 19., 20., 21.]])
tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.],
        [20., 22., 24., 26., 28.],
        [30., 32., 34., 36., 38.]])


* 计算其元素的和

In [91]:
A = torch.arange(40, dtype=torch.float32).reshape(2,5,4)
print(A)
print(A.sum())

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])
tensor(780.)


* 指定求和汇总张量的轴

In [92]:
A_sum_axis0 = A.sum(axis=0)   # 按 2 这个维度进行求和
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]), torch.Size([5, 4]))

In [93]:
A_sum_axis1 = A.sum(axis=1)   # 按 5 行进行求和
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]), torch.Size([2, 4]))

In [94]:
A.sum(axis=[0, 1])

tensor([180., 190., 200., 210.])

* 一个与求和相关的量是 **平均值** (mean/average)

In [108]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [96]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [97]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

 * 计算总和或均值时保持轴数不变，这样就可以利用广播机制

In [98]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [99]:
A.sum(axis=1)  # 变成一维张量

tensor([ 6., 22., 38., 54., 70.])

In [100]:
sum_A = A.sum(axis=1, keepdims=True)  # 依然是二位张量
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [101]:
A / sum_A  # 利用广播机制

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

* 累加求和

In [102]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [103]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

*  点积是相同位置的按元素乘积的和，也就是**对哈达玛积求和**

In [104]:
x = torch.tensor([1.0,2,3,4]) 
y = torch.ones(4,dtype=torch.float32)
x, y 

(tensor([1., 2., 3., 4.]), tensor([1., 1., 1., 1.]))

In [105]:
torch.dot(x, y), torch.sum(x * y)

(tensor(10.), tensor(10.))

* 矩阵-矩阵(向量)乘法 AB(Ax)

In [106]:
A, x, A.shape, x.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([1., 2., 3., 4.]),
 torch.Size([5, 4]),
 torch.Size([4]))

In [107]:
# 个人理解是: 这里的一维向量是按照一维列向量参加运算，输出的时候是行向量形式
torch.mv(A, x)  # matrix - vector  

tensor([ 20.,  60., 100., 140., 180.])

In [111]:
B = torch.ones(4,3)   # matrix - matrix
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

*  $L_2$范数表示向量元素平方和的平方根:  
$$\Vert x\Vert_2 = \sqrt{\sum_{i=1}^{n}x_i^2}$$



In [113]:
u = torch.tensor([3.0, -4.0])
torch.norm()

tensor(5.)

* $L_1$范数表示为向量元素的绝对值之和:
$$\Vert x\Vert_1 = \sum_{i=1}^{n}|x_i|$$

In [114]:
torch.abs(u).sum()

tensor(7.)

矩阵的 **弗罗贝尼乌斯范数(Frobenius norm)** 是矩阵元素的平方和的平方根:
$$\Vert x\Vert_2 = \sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}x_{ij}^2}$$

In [120]:
f = torch.tensor([[4,-3],[3,4]], dtype=torch.float32)
torch.norm(f)

tensor(7.0711)